### ISSUE TITLE
Can't handle tuples(?)

### ISSUE THREAD

**Issue by xhevahir** [wheineman/nrpl#2]
Tuples don't seem to work. I've only tried to use echo() with them so far, but whenever I do I get an error like this: 
'SIGSEGV: Illegal storage access. (Try to compile with -d:useSysAssert -d:useGcAssert for details.) 
Error: execution of an external program failed'

**Comment by wheineman** [comment]
Fixed with latest changes:
$ nrpl
> type
-   Person = tuple[name: string, age: int]
- var
-   person: Person
- person = (name: "Peter", age: 30)
-
> echo(person.name)
Peter
> echo(person.age)
30
>
