### ISSUE TITLE
Unnecessary blank line for one-line declarations

### ISSUE THREAD

**Issue by andreaferretti** [wheineman/nrpl#8]
When `let` or `var` is followed by a value, it is (I think) invalid to have more values following in the same block. In this case, it makes sense to evaluate the line immediately without requiring blank lines

example:

    > let x = 1
    -

Here there is no need for the `-` line

**Comment by wheineman** [comment]
I will address in the next release.

**Comment by wheineman** [comment]
Fixed in version 0.1.4
